### ISSUE TITLE
REQUEST FOR C# EXAMPLE

### ISSUE THREAD

**Issue by ElijahGM** [CodeReaper/unsealed-secrets#2] opened 2017-04-10 18:21 UTC
Can i request for the above

**Comment by CodeReaper** [comment] 2017-04-11 12:17
I have added an example for C# / Mono (I have no Windows machines :))

**Comment by ElijahGM** [comment] 2017-04-11 12:24
For the android code, i get error with my .der file,  does it run on latest android

**Comment by CodeReaper** [comment] 2017-04-11 21:08
I have updated the Android example so it should compile without you needing to make any changes. Could you check it again and if it does not work, please report what kind of error are you getting.

**Comment by CodeReaper** [comment] 2017-04-17 22:00
I am assuming the issue is resolved so I am closing this issue.

**Closed as completed by CodeReaper** 2017-04-17 22:00 UTC

**Comment by ElijahGM** [comment] 2017-04-21 08:30
Works like charm thanks
